import '../tutor.dart';

class ExtendedTutor extends Tutor {
  final List<dynamic> certificationUrls;

  ExtendedTutor.constructor(
    int id,
    String fullname,
    String gender,
    String birthday,
    String email,
    String phone,
    String address,
    String status,
    int roleId,
    String description,
    String avatarImageLink,
    String educationLevel,
    String school,
    int points,
    int membershipId,
    String socialIdUrl,
     String createdDate,
    String confirmedDate,
    this.certificationUrls,
  ) : super.fromJsonConstructor(
          id,
          fullname,
          gender,
          birthday,
          email,
          phone,
          address,
          status,
          roleId,
          description,
          avatarImageLink,
          educationLevel,
          school,
          points,
          membershipId,
          socialIdUrl,
          createdDate,
          confirmedDate,
        );
  ExtendedTutor.fromJsonConstructor({
    int id,
    String fullname,
    String gender,
    String birthday,
    String email,
    String phone,
    String address,
    String status,
    int roleId,
    String description,
    String avatarImageLink,
    String educationLevel,
    String school,
    int points,
    int membershipId,
    String socialIdUrl,
    String createdDate,
    String confirmedDate,
    this.certificationUrls,
  }) : super.fromJsonConstructor(
          id,
          fullname,
          gender,
          birthday,
          email,
          phone,
          address,
          status,
          roleId,
          description,
          avatarImageLink,
          educationLevel,
          school,
          points,
          membershipId,
          socialIdUrl,
          createdDate,
          confirmedDate,
        );

  factory ExtendedTutor.fromJson(Map<String, dynamic> json) {
    return ExtendedTutor.fromJsonConstructor(
      id: json['id'],
      fullname: json['fullname'],
      gender: json['gender'],
      birthday: json['birthday'].toString().substring(0, 10),
      email: json['email'],
      phone: json['phone'],
      address: json['address'],
      status: json['status'].toString(),
      roleId: json['roleId'],
      avatarImageLink: json['avatarImageLink'].toString(),
      educationLevel: json['educationLevel'].toString(),
      school: json['school'].toString(),
      points: json['points'],
      membershipId: json['membershipId'],
      description: json['description'].toString(),
      socialIdUrl: json['socialIdUrl'].toString(),
      certificationUrls: json['certificationUrls'],
      createdDate: json['createdDate'].toString(),
      confirmedDate: json['confirmedDate'],
    );
  }
}

// certificationImage: json['certificationImage'].ToList(),
